# This is a basic workflow to help you get started with Actions

name: 项目打包

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name to create (e.g., v1.2.3)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.head_commit.message, '[cicd]')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 代码检出
        uses: actions/checkout@v4

      # 2. 设置 Java 环境
      - name: 设置JAVA环境
        uses: actions/setup-java@v3
        with:
          java-version: '22'  # Java 版本
          distribution: 'temurin'

      # 3. 构建项目
      - name: 打包
        run: mvn clean package -DskipTests  # Maven 构建（跳过测试）

      # Runs a single command using the runners shell
      - name: 运行单行测试脚本
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: 运行多行测试脚本
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  generate_tag:
      runs-on: ubuntu-latest
      permissions:
        contents: write  # 添加写权限
      steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 创建并推送新标签
      - name: Push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=${{ inputs.tag_name }}
          git tag "$tag_name"
          git push origin "$tag_name"
          echo "New tag_name: $tag_name"
          echo "new_tag=$tag_name" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.generate_tag.outputs.new_tag }}
          release_name: "Release ${{ steps.generate_tag.outputs.new_tag }}"
          body: "This is an automated release."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


   
